sudo: false
language: ruby
rvm:
- 2.3.3
before_install: gem install bundler -v 1.16.0.pre.2
deploy:
  provider: rubygems
  api_key:
    secure: FL18oboOrUK8xa32WsL9eeyfNTwZP4+AOSehnFc/BOynqvMghfCB4amzEkPDIctXtr//75pA29VwM4LuzE5bMbEFnk3joO/GuSBEHOYC6pkECsQjqtOzmy1/3mWiAVRl8jmPSn7lu9PZF0ZJIUaBk7r8LCcIPSSq1nufmlX98hE++5LZobDPmHIQrzYpfPYRczOh3YkDuwaUn8Vw4iqsTlID0m5Qdy9L7mCrjF9W8FtPCo5qhSvcWPOGjOBR9hkM3ZK4h5J6GLrvNitCtGTAzSlDbVmvrOAVk8i/eR1uWfKzed/FQahLnc4YCU8n38MuWCpuYply+UXg10rQ+s6LsSni/IyDOL4Fv8fUHbqidRLD7xVmRJoltEpTAWwLbNFCsEa3hORt2wRLNJgt7Gj0KMS6PrpP5hsMI8ye8aS9fl98/2hgatBGIznjzYJ7hpr7w9HFWlcno1C664hKe4VrwREDLzH8eABCQkpzmFAqyuw8PY4Age9vc1YZg0zoHmg3I5xM515ja4csf23QvkjvINoo115GWhZvtNKnaPyoMuiyTgeUxHAk7e4k0024V1dQllH/c3Nmj7CXIQJKKYt2rK860yzjIy3bXDjnfJk9cW+7wIBAmZYOTahWvQJw0Re4gYr/dIkvPuv2845zVuGGfrekLgqEXGadBqAhlhuGMq4=
  gem: middleman-medium
  on:
    tags: true
    repo: cffiebigc/middleman-medium
